const pets = [
    {
        "id": 1,
        "name": "Siamese",
        "price": 100,
        "quantity": 5,
        "age": 3,
        "color": "multicolored",
        "rapacity": true,
        "type": "cat",
        "gender": "male",
        "fur": "middle",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "lopiness": false,
        "url": "http://funkot.ru/wp-content/uploads/2016/05/siamskii-kot-colorpoint.jpg"
    },
    {
        "id": 2,
        "name": "Siamese",
        "price": 150,
        "quantity": 2,
        "age": 3,
        "color": "multicolored",
        "rapacity": true,
        "type": "cat",
        "gender": "female",
        "fur": "middle",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "lopiness": false,
        "url": "http://lapusiki.com/wp-content/uploads/2017/12/siamskaya-koshka.jpg"
    },
    {
        "id": 3,
        "name": "Scottish",
        "price": 200,
        "quantity": 2,
        "age": 1,
        "color": "blue",
        "rapacity": true,
        "type": "cat",
        "gender": "female",
        "fur": "short",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "lopiness": true,
        "url": "http://pipcat.ru/wp-content/uploads/2016/12/4e56b2dfabd82385277f7c1b8f8e72e9.jpg"
    },
    {
        "id": 4,
        "name": "Persian",
        "price": 300,
        "quantity": 1,
        "age": 2,
        "color": "ginger",
        "rapacity": true,
        "type": "cat",
        "gender": "male",
        "fur": "long",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "lopiness": false,
        "url": "http://lemiki.ru/wp-content/uploads/2017/04/image3.jpeg"
    },
    {
        "id": 5,
        "name": "Sphinx",
        "price": 400,
        "quantity": 3,
        "age": 1,
        "color": "body",
        "rapacity": true,
        "type": "cat",
        "gender": "male",
        "fur": "bald",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "lopiness": false,
        "url": "https://petstory.ru/resize/800x800x80/upload/images/articles/breeds/canadian-sphynx/canadian-sphynx_3.jpg"
    },
    {
        "id": 6,
        "name": "Sphinx",
        "price": 500,
        "quantity": 3,
        "age": 1,
        "color": "body",
        "rapacity": true,
        "type": "cat",
        "gender": "female",
        "fur": "bald",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "lopiness": false,
        "url": "http://catfur.ru/uploads/posts/2014-06/1403251057_1.jpg"
    },
    {
        "id": 7,
        "name": "Munchkin",
        "price": 500,
        "quantity": 3,
        "age": 1,
        "color": "multicolored",
        "rapacity": true,
        "type": "cat",
        "gender": "female",
        "fur": "long",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": true,
        "lopiness": false,
        "url": "http://pipcat.ru/wp-content/uploads/2016/09/koshka_manchkin_3_23192416.jpg"
    },
    {
        "id": 8,
        "name": "Shepherd",
        "price": 250,
        "quantity": 1,
        "age": 2,
        "color": "black",
        "rapacity": true,
        "type": "dog",
        "gender": "female",
        "fur": "long",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "specialization": "security",
        "url": "https://petsi.net/images/dogbreed/big/10.jpg"
    },
    {
        "id": 9,
        "name": "Shepherd",
        "price": 250,
        "quantity": 1,
        "age": 2,
        "color": "black",
        "rapacity": true,
        "type": "dog",
        "gender": "male",
        "fur": "long",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "specialization": "security",
        "url": "https://vignette.wikia.nocookie.net/doge/images/5/53/%D0%9D%D0%B5%D0%BC%D0%B5%D1%86%D0%BA%D0%B0%D1%8F_%D0%BE%D0%B2%D1%87%D0%B0%D1%80%D0%BA%D0%B0.jpg/revision/latest?cb=20180325231507&path-prefix=ru"
    },
    {
        "id": 10,
        "name": "Alabai",
        "price": 500,
        "quantity": 1,
        "age": 2,
        "color": "white",
        "rapacity": true,
        "type": "dog",
        "gender": "male",
        "fur": "short",
        "pedigree": true,
        "dockedTail": true,
        "shortPaws": false,
        "specialization": "security",
        "url": "https://opt-1031816.ssl.1c-bitrix-cdn.ru/upload/resize_cache/iblock/e9b/750_400_1/sredneaziatskaja_ovcharka.jpg?1528236061179721"
    },
    {
        "id": 11,
        "name": "Dachshund",
        "price": 200,
        "quantity": 3,
        "age": 1,
        "color": "ginger",
        "rapacity": true,
        "type": "dog",
        "gender": "male",
        "fur": "short",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": true,
        "specialization": "hunting",
        "url": "https://www.royal-canin.ru/upload/iblock/f09/taksa.jpg"
    },
    {
        "id": 12,
        "name": "Dachshund",
        "price": 300,
        "quantity": 5,
        "age": 1,
        "color": "black",
        "rapacity": true,
        "type": "dog",
        "gender": "female",
        "fur": "short",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": true,
        "specialization": "hunting",
        "url": "https://avatars.mds.yandex.net/get-pdb/1368870/f16f8e50-ef06-4c66-90ad-f1b3cef559cf/s1200"
    },
    {
        "id": 13,
        "name": "Сhihuahua",
        "price": 300,
        "quantity": 1,
        "age": 2,
        "color": "body",
        "rapacity": true,
        "type": "dog",
        "gender": "female",
        "fur": "short",
        "pedigree": true,
        "dockedTail": false,
        "shortPaws": false,
        "specialization": "decorative",
        "url": "https://podrobnosti.ua/media/pictures/2017/6/9/thumbs/740x415/foto-iz-otkrytyh-istochnikov_rect_8698a69167e1769719db5adeb23e27bf.jpg"
    },
    {
        "id": 14,
        "name": "Bulldog",
        "price": 400,
        "quantity": 1,
        "age": 1,
        "color": "multicolored",
        "rapacity": true,
        "type": "dog",
        "gender": "male",
        "fur": "short",
        "pedigree": true,
        "dockedTail": true,
        "shortPaws": false,
        "specialization": "fighting",
        "url": "https://moypitomets.com/sites/default/files/styles/statya/public/bulldogs-3-645mk062111.jpg?itok=0Jpz6Js8"
    },
    {
        "id": 15,
        "name": "Swordfish",
        "price": 20,
        "quantity": 10,
        "age": 1,
        "color": "red",
        "rapacity": false,
        "type": "fish",
        "gender": "male",
        "freshwater": true,
        "zone": "top",
        "url": "https://images.ua.prom.st/130634198_mechenosets-rubinovyj.jpg"
    },
    {
        "id": 16,
        "name": "Swordfish",
        "price": 30,
        "quantity": 15,
        "age": 1,
        "color": "red",
        "rapacity": false,
        "type": "fish",
        "gender": "female",
        "freshwater": true,
        "zone": "top",
        "url": "http://s3.fotokto.ru/photo/full/561/5614700.jpg"
    },
    {
        "id": 17,
        "name": "Catfish",
        "price": 50,
        "quantity": 1,
        "age": 3,
        "color": "black",
        "rapacity": false,
        "type": "fish",
        "gender": "female",
        "freshwater": true,
        "zone": "bottom",
        "url": "https://rybki.guru/wp-content/uploads/2018/07/ancistrus_-min.jpg"
    },
    {
        "id": 18,
        "name": "Gourami",
        "price": 100,
        "quantity": 3,
        "age": 2,
        "color": "blue",
        "rapacity": false,
        "type": "fish",
        "gender": "female",
        "freshwater": true,
        "zone": "top",
        "url": "http://voboze.ru/upload/000/u1/d7/cb/gurami-mramornye-v-akvariume-soderzhanie-sovmestimost-chem-kor.jpg"
    },
    {
        "id": 19,
        "name": "Gourami",
        "price": 100,
        "quantity": 3,
        "age": 2,
        "color": "silver",
        "rapacity": false,
        "type": "fish",
        "gender": "female",
        "freshwater": true,
        "zone": "top",
        "url": "https://pets2.me/media/res/4/1/4/414.oqt8to.620.jpg"
    },
    {
        "id": 20,
        "name": "Amphiprion",
        "price": 500,
        "quantity": 1,
        "age": 1,
        "color": "multicolored",
        "rapacity": true,
        "type": "fish",
        "gender": "female",
        "freshwater": false,
        "zone": "top",
        "url": "https://images.ru.prom.st/458392294_w1493_h430_amfiprion-otsellyaris-amphiprion.jpg"
    },
    {
        "id": 21,
        "name": "Zebrasoma",
        "price": 500,
        "quantity": 1,
        "age": 1,
        "color": "yellow",
        "rapacity": true,
        "type": "fish",
        "gender": "female",
        "freshwater": false,
        "zone": "top",
        "url": "http://aquamir-za-steklom.ru/wp-content/uploads/2016/09/Zebrasoma-flavescens.jpg"
    },
    {
        "id": 22,
        "name": "Agapornis",
        "price": 50,
        "quantity": 7,
        "age": 1,
        "color": "yellow",
        "rapacity": false,
        "type": "bird",
        "gender": "female",
        "canfly": true,
        "canSpeak": false,
        "url": "https://img.superzoo.cz/img/school_article/727.jpg"
    },
    {
        "id": 23,
        "name": "Agapornis",
        "price": 100,
        "quantity": 3,
        "age": 1,
        "color": "green",
        "rapacity": false,
        "type": "bird",
        "gender": "female",
        "canfly": true,
        "canSpeak": false,
        "url": "https://www.joelsartore.com/assets/stock/BIR068/BIR068-00384-700x467.jpg"
    },
    {
        "id": 24,
        "name": "Cockatoo",
        "price": 500,
        "quantity": 1,
        "age": 1,
        "color": "white",
        "rapacity": false,
        "type": "bird",
        "gender": "male",
        "canfly": true,
        "canSpeak": true,
        "url": "https://www.zoospravka.ru/Bird/images/cacatua_sulphurea.jpg"
    },
    {
        "id": 25,
        "name": "Melopsittacus",
        "price": 100,
        "quantity": 1,
        "age": 1,
        "color": "blue",
        "rapacity": false,
        "type": "bird",
        "gender": "female",
        "canfly": true,
        "canSpeak": false,
        "url": "https://www.krasnouhie.ru/wp-content/uploads/2016/12/456.jpg"
    }
];

export {pets};